spring:
  datasource:
    url: jdbc:h2:file:./cash_card
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations:
        classpath: schema.sql
      data-locations:
        classpath: data.sql
      mode: always
logging:
  level:
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
    org.springframework.boot.autoconfigure.sql.init: DEBUG



