spring:
  datasource:
    url: jdbc:h2:file:./UIT_SCHEDULE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always
      data-locations:
        classpath: data.sql
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  logging:
    level:
      org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
      org.springframework.boot.autoconfigure.sql.init: DEBUG
      org.springframework.web: DEBUG
      org.hibernate: DEBUG
      org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
      org.springframework.web.servlet.DispatcherServlet: DEBUG

    file:
      name: logs/application.log




