//DROP TABLE IF EXISTS PTSTUDENTS;
//DROP TABLE IF EXISTS SHIFT;
//DROP TABLE IF EXISTS SCHEDULE;
//DROP TABLE IF EXISTS AVAILABILITY;

CREATE TABLE IF NOT EXISTS PTSTUDENTS
(
    Id INTEGER AUTO_INCREMENT PRIMARY KEY ,
    name VARCHAR(20),
    phone VARCHAR(20),
    hoursAllowed DOUBLE,
    availabilities INTEGER
);

CREATE TABLE IF NOT EXISTS SHIFT
(
    shiftId INTEGER AUTO_INCREMENT PRIMARY KEY ,
    shiftDescription VARCHAR(20),
    hours DOUBLE,
    availabilities INTEGER
);

CREATE TABLE IF NOT EXISTS SCHEDULE
(
    scheduleId INTEGER AUTO_INCREMENT PRIMARY KEY,
    day_of_week VARCHAR(20),
    availability INTEGER
);

CREATE TABLE IF NOT EXISTS AVAILABILITY
(
    availabilityId INTEGER AUTO_INCREMENT PRIMARY KEY ,
    studentId INTEGER,
    shiftId INTEGER,
    scheduleId INTEGER,

    CONSTRAINT fk_PtStudent
            FOREIGN KEY (studentId)
            REFERENCES PTSTUDENTS(Id)
            ON DELETE CASCADE,

    CONSTRAINT fk_Shift
        FOREIGN KEY (shiftId)
            REFERENCES SHIFT(shiftId)
            ON DELETE CASCADE,

    CONSTRAINT fk_Schedule
        FOREIGN KEY (scheduleId)
            REFERENCES SCHEDULE(scheduleId)
            ON DELETE CASCADE
);

